const GOT_RED_LINE_ROUTE = 'GOT_RED_LINE_ROUTE'
const GOT_BROWN_LINE_ROUTE = 'GOT_BROWN_LINE_ROUTE'
const GOT_BLUE_LINE_ROUTE = 'GOT_BLUE_LINE_ROUTE'
const TOGGLED_TRAIN_ROUTE = 'TOGGLED_TRAIN_ROUTE'
const COUNT_GOOGLE_MAPS_API_CALLS = 'COUNT_GOOGLE_MAPS_API_CALLS'

export default {
  GOT_RED_LINE_ROUTE,
  GOT_BROWN_LINE_ROUTE,
  GOT_BLUE_LINE_ROUTE,
  TOGGLED_TRAIN_ROUTE,
  COUNT_GOOGLE_MAPS_API_CALLS
}
