const GOT_RED_LINE_ROUTE = 'GOT_RED_LINE_ROUTE'
const GOT_BROWN_LINE_ROUTE = 'GOT_BROWN_LINE_ROUTE'
const TOGGLED_TRAIN_ROUTE = 'TOGGLED_TRAIN_ROUTE'

export default {
  GOT_RED_LINE_ROUTE,
  GOT_BROWN_LINE_ROUTE,
  TOGGLED_TRAIN_ROUTE
}
